on: 
  push: 
    branches: 
      - main
jobs: 
  build: 
    name: build the static site
    runs-on: ubuntu-latest
    steps: 
     - name: Checkout repo
       uses: actions/checkout@v5
     
     - name: Use Node.js 24
       uses: actions/setup-node@v4
       with:
          node-version: 24

     - name: Setup pnpm
       uses: pnpm/action-setup@v2
       with:
         version: 8

     - name: Install dependencies
       run: pnpm install

     - name: Build Astro
       run: pnpm build

      # --- Deploy to server ---
     - name: Copy files to server via SSH
       uses: appleboy/scp-action@v0.1.4
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{ secrets.SSH_KEY }}
         source: "dist/*"
         target: "~/sites/blog/"
